package com.CAPSTONEPROJECT.CAPSTONE.service.impl;

import com.CAPSTONEPROJECT.CAPSTONE.dto.LoginRequestDTO;
import com.CAPSTONEPROJECT.CAPSTONE.dto.LoginResponseDTO;
import com.CAPSTONEPROJECT.CAPSTONE.dto.RegisterRequestDTO;
import com.CAPSTONEPROJECT.CAPSTONE.entity.User;
import com.CAPSTONEPROJECT.CAPSTONE.exception.InvalidCredentialsException;
import com.CAPSTONEPROJECT.CAPSTONE.repository.UserRepository;
import com.CAPSTONEPROJECT.CAPSTONE.service.AuthService;
import lombok.RequiredArgsConstructor;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

/**
 * AuthServiceImpl
 *
 * LOGIN (UNCHANGED):
 *   Username + BCrypt password check → returns JWT (via AuthController).
 *
 * REGISTER (UPDATED):
 *   Now also accepts + validates + saves the email field.
 *   Email uniqueness is checked at service level BEFORE hitting the DB
 *   so the user gets a clear friendly error instead of a raw constraint violation.
 */
@Service
@RequiredArgsConstructor
public class AuthServiceImpl implements AuthService {

    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;

    // -----------------------------------------------------------------------
    // LOGIN — DO NOT MODIFY (JWT is generated in AuthController)
    // -----------------------------------------------------------------------
    @Override
    public LoginResponseDTO login(LoginRequestDTO request) {

        User user = userRepository.findByUsername(request.getUsername())
                .orElseThrow(() -> new InvalidCredentialsException("Invalid username or password"));

        if (!passwordEncoder.matches(request.getPassword(), user.getPassword())) {
            throw new InvalidCredentialsException("Invalid username or password");
        }

        // NOTE: actual JWT token is generated by AuthController using AuthenticationManager.
        // This path is kept for backward compatibility.
        return new LoginResponseDTO("Login successful", user.getRole().name());
    }

    // -----------------------------------------------------------------------
    // REGISTER — updated to include email and role string conversion
    // -----------------------------------------------------------------------
    @Override
    public void register(RegisterRequestDTO request) {

        // 1) Block duplicate usernames
        if (userRepository.findByUsername(request.getUsername()).isPresent()) {
            throw new IllegalArgumentException("User already exists");
        }

        // 2) Block duplicate emails
        //    WHY: Two users sharing the same email would cause confusion
        //    in password-reset emails and break the unique DB constraint.
        if (userRepository.existsByEmail(request.getEmail())) {
            throw new IllegalArgumentException(
                    "Email '" + request.getEmail() + "' is already registered.");
        }

        // 3) Convert role string to enum
        //    Frontend sends "CUSTOMER" or "OWNER" as string, we convert it to Role enum
        com.CAPSTONEPROJECT.CAPSTONE.entity.Role roleEnum;
        try {
            roleEnum = com.CAPSTONEPROJECT.CAPSTONE.entity.Role.valueOf(request.getRole().toUpperCase());
        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException(
                    "Invalid role: '" + request.getRole() + "'. Must be CUSTOMER or OWNER.");
        }

        // 4) Build and save the new user with BCrypt-encoded password
        User newUser = User.builder()
                .username(request.getUsername())
                .email(request.getEmail())  // save email so reset-password emails can be sent
                .password(passwordEncoder.encode(request.getPassword()))
                .role(roleEnum)  // set the converted role enum
                .build();

        userRepository.save(newUser);
    }
}
